"""
Stage 7's acceptance criterion: a fixed phenotype gives a byte-identical `.mhm`.

The golden file is the point of this module. Every other test here checks one
mapping in isolation, but only the golden comparison catches the failure that
actually costs something: a change to the emission order, the float format or
the header that leaves every individual mapping correct while making last
month's baked village unreproducible.

`tests/fixtures/golden_villager.mhm` is regenerated by running

    python -m tests.test_phenotype_to_mhm --write-golden

and regenerating it is a decision, not a fix. If the golden file changes, every
`.mhm` and every FBX baked from one is stale.
"""

from __future__ import annotations

import ast
import pathlib

import pytest

from health_engine.phenotype_to_mhm import (
    DEFAULT_ETHNICITY,
    ETHNICITY_PRESETS,
    NEUTRAL_MACROS,
    age_to_macro,
    bmi_to_weight_macro,
    macros_to_mhm,
    phenotype_to_macros,
    phenotype_to_mhm,
    pigmentation,
)

FIXTURES = pathlib.Path(__file__).parent / "fixtures"
GOLDEN = FIXTURES / "golden_villager.mhm"
REPO = pathlib.Path(__file__).resolve().parents[1]

# One fixed phenotype, deliberately not neutral on any axis this module drives.
# The pigmentation entries are here so the test that they stay OUT of the
# `.mhm` has something to fail on.
GOLDEN_PHENOTYPE = {
    "bmi": 27.3,
    "adiposity": 0.8,
    "height_cm": 181.4,
    "skin_tone": 0.31,
    "hair_pigment": 0.72,
    "eye_color": "hazel",
    "aerobic_capacity": 48.2,
}
GOLDEN_ARGS = dict(sex="female", age_years=34.0, name="golden_villager")


def _golden_text() -> str:
    return phenotype_to_mhm(GOLDEN_PHENOTYPE, **GOLDEN_ARGS)


# ----------------------------------------------------------------------
# the acceptance criterion
# ----------------------------------------------------------------------

def test_golden_mhm_is_byte_identical():
    assert GOLDEN.exists(), (
        f"{GOLDEN} is missing; regenerate with "
        "`python -m tests.test_phenotype_to_mhm --write-golden` and read the "
        "module docstring before committing it")
    assert _golden_text() == GOLDEN.read_text(encoding="utf-8")


def test_output_is_deterministic_across_calls():
    assert _golden_text() == _golden_text()


def test_no_crlf_leaks_into_the_output():
    # The bake runs on Windows and the golden file is read back as text. A
    # stray "\r" would make the comparison pass locally and fail on any other
    # machine, which is the reproducibility defect this project already had
    # once.
    assert "\r" not in _golden_text()


# ----------------------------------------------------------------------
# the age mapping, which is the one that is assumed rather than measured
# ----------------------------------------------------------------------

@pytest.mark.parametrize("years,expected", [(1.0, 0.0), (25.0, 0.5), (90.0, 1.0)])
def test_age_macro_hits_makehuman_anchors(years, expected):
    assert age_to_macro(years) == pytest.approx(expected)


@pytest.mark.parametrize("years", [-5.0, 0.0, 0.9])
def test_age_macro_clamps_below_one_year(years):
    # MakeHuman's youngest body is a one-year-old. Infants clamp rather than
    # raise, so one newborn cannot fail a whole village bake.
    assert age_to_macro(years) == 0.0


def test_age_macro_clamps_above_ninety():
    assert age_to_macro(140.0) == 1.0


def test_age_macro_is_monotone():
    values = [age_to_macro(y) for y in range(1, 100)]
    assert values == sorted(values)


def test_age_macro_slopes_differ_either_side_of_twentyfive():
    # The mapping is piecewise linear in YEARS, so ten years of childhood must
    # move the macro further than ten years of middle age. A single linear
    # mapping would pass every anchor test above and fail this one.
    young = age_to_macro(15.0) - age_to_macro(5.0)
    old = age_to_macro(55.0) - age_to_macro(45.0)
    assert young > old


# ----------------------------------------------------------------------
# the weight mapping
# ----------------------------------------------------------------------

def test_population_mean_bmi_gives_the_neutral_macro():
    assert bmi_to_weight_macro(24.5) == pytest.approx(0.5)


def test_weight_macro_is_monotone_in_bmi():
    values = [bmi_to_weight_macro(b) for b in range(14, 46)]
    assert values == sorted(values)


@pytest.mark.parametrize("bmi", [-10.0, 0.0, 200.0])
def test_weight_macro_stays_in_range(bmi):
    assert 0.0 <= bmi_to_weight_macro(bmi) <= 1.0


def test_weight_macro_saturates_at_the_declared_spread():
    # 2.5 sd is the documented saturation point, so 24.5 + 2.5*4.0 = 34.5.
    assert bmi_to_weight_macro(34.5) == pytest.approx(1.0)
    assert bmi_to_weight_macro(14.5) == pytest.approx(0.0)


def test_missing_bmi_leaves_the_weight_macro_neutral():
    macros = phenotype_to_macros({}, "male", 30.0)
    assert macros["Weight"] == NEUTRAL_MACROS["Weight"]


# ----------------------------------------------------------------------
# the refusals: macros this module must not drive
# ----------------------------------------------------------------------

@pytest.mark.parametrize("macro", ["Height", "BodyProportions", "Muscle"])
def test_undriven_macros_stay_neutral_whatever_the_phenotype(macro):
    # Invariant 5. If a later change starts driving one of these, this test is
    # where the argument has to be made, and the module docstring is where the
    # reason it was not driven is written down.
    loud = dict(GOLDEN_PHENOTYPE)
    loud.update(height_cm=205.0, bmi=41.0, aerobic_capacity=62.0, adiposity=2.9)
    macros = phenotype_to_macros(loud, "male", 41.0)
    assert macros[macro] == NEUTRAL_MACROS[macro]


def test_stature_never_reaches_the_height_macro():
    # The stronger form of the same rule: two villagers differing only in
    # stature must produce identical `.mhm` text, because stature arrives in
    # Unity through the mesh scale instead.
    short = phenotype_to_mhm({"height_cm": 152.0, "bmi": 24.5}, "female", 30.0)
    tall = phenotype_to_mhm({"height_cm": 194.0, "bmi": 24.5}, "female", 30.0)
    assert short == tall


def test_ethnicity_is_fixed_and_not_derived():
    a = phenotype_to_mhm(GOLDEN_PHENOTYPE, "female", 30.0)
    b = phenotype_to_mhm(dict(GOLDEN_PHENOTYPE, skin_tone=0.95), "female", 30.0)
    assert a == b


def test_ethnicity_presets_match_the_blender_side():
    """The duplicated preset table must not drift from `mpfb/blender_probe.py`.

    Read with `ast` rather than imported: that module imports `bpy` at call
    time and only runs inside Blender, so this is the only way a bare pytest
    process can check the two tables agree.
    """
    source = (REPO / "mpfb" / "blender_probe.py").read_text(encoding="utf-8")
    tree = ast.parse(source)
    found = None
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
                getattr(t, "id", None) == "ETHNICITY_PRESETS" for t in node.targets):
            found = node
    assert found is not None, "ETHNICITY_PRESETS not found in mpfb/blender_probe.py"

    blender_side = {}
    for key_node, value_node in zip(found.value.keys, found.value.values):
        preset = {}
        for kw in value_node.keywords:
            preset[kw.arg.lower()] = ast.literal_eval(kw.value)
        blender_side[ast.literal_eval(key_node)] = preset

    ours = {name: {k.lower(): v for k, v in preset.items()}
            for name, preset in ETHNICITY_PRESETS.items()}
    assert ours == blender_side


# ----------------------------------------------------------------------
# pigmentation stays out of the morph file
# ----------------------------------------------------------------------

@pytest.mark.parametrize("key", ["skin_tone", "hair_pigment", "eye_color"])
def test_pigmentation_never_appears_in_the_mhm(key):
    assert key not in _golden_text()


def test_pigmentation_is_returned_separately():
    out = pigmentation(GOLDEN_PHENOTYPE)
    assert out["skin_tone"] == pytest.approx(0.31)
    assert out["eye_color"] == "hazel"
    assert "bmi" not in out


def test_pigmentation_tolerates_a_phenotype_missing_every_key():
    assert pigmentation({"bmi": 22.0}) == {}


# ----------------------------------------------------------------------
# format and validation
# ----------------------------------------------------------------------

def test_sex_drives_the_gender_macro():
    assert phenotype_to_macros({}, "male", 30.0)["Gender"] == 1.0
    assert phenotype_to_macros({}, "female", 30.0)["Gender"] == 0.0


@pytest.mark.parametrize("sex", ["M", "F", "Male", "", None])
def test_unknown_sex_is_rejected(sex):
    # The engine spells these "male" and "female" (health_engine/npc.py:64).
    # Silently treating "M" as neutral would give a village of androgynes and
    # no error anywhere.
    with pytest.raises(ValueError):
        phenotype_to_macros({}, sex, 30.0)


def test_unknown_ethnicity_is_rejected():
    with pytest.raises(ValueError):
        phenotype_to_macros({}, "male", 30.0, ethnicity="martian")


def test_incomplete_macro_vector_is_rejected():
    partial = dict(NEUTRAL_MACROS)
    partial.pop("Muscle")
    partial.update(ETHNICITY_PRESETS[DEFAULT_ETHNICITY])
    with pytest.raises(KeyError):
        macros_to_mhm(partial)


def test_the_game_engine_rig_is_the_default():
    # With no rig, or with a non-game rig, the FBX loses the unit round trip
    # and the Z-up to Y-up correction and arrives in Unity 100x small and
    # lying down. `run_mpfb_probe.py` asserts both as failures on purpose.
    assert "skeleton game_engine.mhskel" in _golden_text()


def test_every_driven_macro_is_emitted_once():
    lines = [ln for ln in _golden_text().splitlines() if ln.startswith("modifier ")]
    names = [ln.split()[1] for ln in lines]
    assert len(names) == len(set(names)) == 9


def test_values_use_six_decimals():
    for line in _golden_text().splitlines():
        if line.startswith("modifier "):
            assert len(line.split()[2].split(".")[1]) == 6


if __name__ == "__main__":  # pragma: no cover
    import sys

    if "--write-golden" in sys.argv:
        FIXTURES.mkdir(exist_ok=True)
        GOLDEN.write_text(_golden_text(), encoding="utf-8", newline="")
        print(f"wrote {GOLDEN}")
    else:
        print(__doc__)
