"""Photograph the family as a lineup, front on (UNITY_PLAN Stage 8's own question).

WHY THIS EXISTS SEPARATELY FROM `unity_village.py`. The village shots answer
"are these people rather than capsules", which Stage 6 asked. Stage 8 asks
something the village camera physically cannot show: **does genotype-driven
variation alone read as a family and a population, or does everyone look like
a recolour of one person?** From 34 metres up, twenty humans are twenty dots,
and a dot has no build. The bodies have to stand side by side, at the same
distance, facing the camera, before anyone can say whether they differ.

WHAT THIS IS HONEST ABOUT BEING. It is NOT a picture of the simulation. It
arranges villagers in a row they never stood in, which is exactly the thing
`unity_village.py` refuses to do to its own subject. That is fine here because
this harness does not claim to show the world; it is a contact sheet of the
bodies the world produced, and it is named so nobody mistakes one for the
other.

THE SKIN IS DELIBERATELY UNIFORM. In the village the lineage colour tints the
whole villager, which is item A5 and is the reason the wide shot is full of
magenta people. Here every body gets the same neutral material, because the
question is about SHAPE and a colour difference is the fastest way to make two
identical shapes look different. Removing the confound is the point.

WHAT VARIES IN THESE BODIES, so the picture is read correctly:

  * sex, age and body mass vary through the morph targets, per villager;
  * stature varies through the Unity scale, NOT the mesh, because every baked
    body is normalised to 1 m (see `HumanMesh`);
  * musculature, body proportions and the ethnicity macro do NOT vary at all,
    and cannot, because the engine has no trait behind any of them. Items E4,
    E5 and U5 respectively.

So if this lineup looks monotonous, the honest reading is not "the genetics
does nothing". It is "sex, age and mass are the only channels currently
connected", which is a smaller and more useful claim.
"""

from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

MARKER = "[LINEUP]"

LINEUP_CS = r'''
using System.Collections.Generic;
using System.Text;
using ExtNPC.View;
using Newtonsoft.Json.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

// Generated by mpfb/unity_lineup.py. Not tracked, not part of the package.
public static class ShootBodyLineup
{
    private const string Marker = "[LINEUP]";

    private sealed class Body
    {
        public string Name;
        public bool Female;
        public double Age;
        public double HeightCm;
        public double PedigreeF;
        public string Mother, Father;
    }

    public static void Run()
    {
        var c = System.Globalization.CultureInfo.InvariantCulture;
        var sb = new StringBuilder();
        string bundle = System.Environment.GetEnvironmentVariable("EXTNPC_BUNDLE");
        string outDir = System.Environment.GetEnvironmentVariable("EXTNPC_LINEUP_OUT");

        HumanMesh.Forget();
        BodyLibrary.Forget();
        EditorSceneManager.NewScene(NewSceneSetup.DefaultGameObjects,
                                    NewSceneMode.Single);

        string manifestPath = System.IO.Path.Combine(bundle, "bodies",
                                                     BodyLibrary.ManifestName);
        if (!System.IO.File.Exists(manifestPath))
        {
            sb.AppendLine($"{Marker} BEGIN load");
            sb.AppendLine($"{Marker} error=no bodies.json at " + manifestPath);
            sb.AppendLine($"{Marker} END");
            Debug.Log(sb.ToString());
            EditorApplication.Exit(1);
            return;
        }

        string json = System.IO.File.ReadAllText(manifestPath);
        BodyLibrary.LoadManifest(json);
        var root = JObject.Parse(json);

        var bodies = new List<Body>();
        foreach (var e in (JArray)root["bodies"])
        {
            bodies.Add(new Body
            {
                Name = (string)e["name"],
                Female = ((string)e["sex"]) == "female",
                Age = (double)e["age"],
                HeightCm = (double)e["height_cm"],
                PedigreeF = (double?)e["pedigree_f"] ?? 0.0,
                Mother = (string)e["mother"],
                Father = (string)e["father"],
            });
        }
        bodies.Sort((a, b) => a.Age.CompareTo(b.Age));

        sb.AppendLine($"{Marker} BEGIN load");
        sb.AppendLine($"{Marker} declared=" + BodyLibrary.Declared.ToString(c));
        sb.AppendLine($"{Marker} ethnicity=" + BodyLibrary.EthnicityPreset);
        sb.AppendLine($"{Marker} END");

        // One neutral material for everyone: see the module docstring. Shader
        // lookup rather than a literal, so this works in URP and built-in.
        Shader lit = Shader.Find("Universal Render Pipeline/Lit")
                     ?? Shader.Find("Standard");
        var skin = new Material(lit);
        skin.color = new Color(0.86f, 0.71f, 0.60f);

        var lightGo = new GameObject("KeyLight");
        var light = lightGo.AddComponent<Light>();
        light.type = LightType.Directional;
        light.intensity = 1.15f;
        lightGo.transform.rotation = Quaternion.Euler(38f, 205f, 0f);

        const float spacing = 0.72f;
        float x = 0f;
        int drawn = 0, ownBody = 0;
        float tallest = 0f;
        foreach (var b in bodies)
        {
            Mesh mesh = BodyLibrary.UnitBodyFor(b.Name, b.Female);
            if (mesh == null) continue;

            // Did this villager get their OWN body, or fall back to the shared
            // one for their sex? Counted rather than assumed: a lineup drawn
            // entirely from two shared meshes would look like a family for the
            // wrong reason, and nothing on screen would say so.
            bool own = mesh.name != null && mesh.name.StartsWith("extnpc_body_");
            if (own) ownBody++;

            var go = new GameObject(b.Name);
            go.AddComponent<MeshFilter>().sharedMesh = mesh;
            go.AddComponent<MeshRenderer>().sharedMaterial = skin;
            float h = (float)(b.HeightCm * 0.01);
            go.transform.localScale = Vector3.one * h;
            go.transform.position = new Vector3(x, 0f, 0f);
            // MPFB's base mesh faces +Z once the FBX round trip has put it in
            // Unity's left-handed Y-up space, and the camera stands at -Z. Not
            // turning them gives a contact sheet of eighteen backs, which is
            // the one view that hides build and hides face together.
            go.transform.rotation = Quaternion.Euler(0f, 180f, 0f);
            x += spacing;
            drawn++;
            if (h > tallest) tallest = h;
        }

        sb.AppendLine($"{Marker} BEGIN scene");
        sb.AppendLine($"{Marker} drawn=" + drawn.ToString(c));
        sb.AppendLine($"{Marker} own_body=" + ownBody.ToString(c));
        sb.AppendLine($"{Marker} loaded_meshes=" + BodyLibrary.Loaded.ToString(c));
        sb.AppendLine($"{Marker} tallest_m=" + tallest.ToString("F4", c));
        sb.AppendLine($"{Marker} END");

        float width = System.Math.Max(x - spacing, 1f);
        float centre = width * 0.5f;
        // Far enough back to fit the row, high enough to look at chest height.
        float dist = width * 0.62f + 1.9f;
        Shoot(sb, outDir, "lineup_all",
              new Vector3(centre, tallest * 0.55f, -dist),
              new Vector3(centre, tallest * 0.48f, 0f), 46f);

        Debug.Log(sb.ToString());
        EditorApplication.Exit(0);
    }

    private static void Shoot(StringBuilder sb, string outDir, string name,
                              Vector3 from, Vector3 lookAt, float fov)
    {
        var c = System.Globalization.CultureInfo.InvariantCulture;
        var camGo = new GameObject("ShotCam");
        var cam = camGo.AddComponent<Camera>();
        cam.fieldOfView = fov;
        cam.clearFlags = CameraClearFlags.SolidColor;
        cam.backgroundColor = new Color(0.10f, 0.11f, 0.13f);
        cam.nearClipPlane = 0.05f;
        cam.farClipPlane = 500f;
        camGo.transform.position = from;
        camGo.transform.LookAt(lookAt);

        var rt = new RenderTexture(1600, 540, 24) { antiAliasing = 4 };
        rt.Create();
        cam.targetTexture = rt;
        cam.Render();

        var shot = new Texture2D(rt.width, rt.height, TextureFormat.RGBA32, false);
        RenderTexture prev = RenderTexture.active;
        RenderTexture.active = rt;
        shot.ReadPixels(new Rect(0, 0, rt.width, rt.height), 0, 0);
        shot.Apply();
        RenderTexture.active = prev;

        sb.AppendLine($"{Marker} BEGIN {name}");
        if (!string.IsNullOrEmpty(outDir))
        {
            System.IO.Directory.CreateDirectory(outDir);
            string file = System.IO.Path.Combine(outDir, name + ".png");
            System.IO.File.WriteAllBytes(file, shot.EncodeToPNG());
            sb.AppendLine($"{Marker} png=" + file);
        }
        double sum = 0.0;
        Color32[] px = shot.GetPixels32();
        foreach (var p in px) sum += (p.r + p.g + p.b) / 3.0;
        sb.AppendLine($"{Marker} mean_luma=" + (sum / px.Length).ToString("F2", c));
        sb.AppendLine($"{Marker} END");

        cam.targetTexture = null;
        RenderTexture.active = null;
        rt.Release();
        Object.DestroyImmediate(shot);
        Object.DestroyImmediate(rt);
        Object.DestroyImmediate(camGo);
    }
}
'''


def shoot(project: Path, log_dir: Path, editor: Path, bundle: Path,
          png_dir: Path) -> dict:
    """One pass. The bodies must already be installed under Assets/Resources."""
    import run_unity_tests as rut
    from mpfb import unity_measure

    rut.ensure_project(editor, project, log_dir)
    editor_dir = project / "Assets" / "Editor"
    editor_dir.mkdir(parents=True, exist_ok=True)
    (editor_dir / "ShootBodyLineup.cs").write_text(LINEUP_CS, encoding="utf-8")
    png_dir.mkdir(parents=True, exist_ok=True)

    log = log_dir / "mpfb-lineup.log"
    if log.exists():
        log.unlink()
    env = dict(os.environ,
               EXTNPC_BUNDLE=str(bundle),
               EXTNPC_LINEUP_OUT=str(png_dir))
    cmd = [str(editor), "-batchmode", "-accept-apiupdate",
           "-logFile", str(log), "-projectPath", str(project),
           "-executeMethod", "ShootBodyLineup.Run"]
    print("  shooting the lineup")
    proc = subprocess.run(cmd, timeout=1800, env=env)
    if not log.exists():
        raise SystemExit("no editor log")
    result = unity_measure._parse(
        log.read_text(encoding="utf-8", errors="replace"), marker=MARKER)
    result["_exit"] = {"code": proc.returncode}
    return result


def report(result: dict) -> int:
    """Print the verdict. Non-zero when the picture cannot answer the question."""
    scene = result.get("scene", {})
    load = result.get("load", {})
    drawn = int(scene.get("drawn", 0))
    own = int(scene.get("own_body", 0))
    declared = int(load.get("declared", 0))

    print(f"\n  declared {declared}, drawn {drawn}, "
          f"own body {own}, ethnicity {load.get('ethnicity', '?')}")

    if drawn == 0:
        print("  [FAIL] nothing was drawn.")
        return 1
    # The check that matters. A lineup where every villager fell back to the
    # shared mesh would still look like a row of people and would prove
    # nothing at all about the genetics.
    if own < drawn:
        print(f"  [FAIL] {drawn - own} of {drawn} villagers fell back to a "
              f"shared body, so this picture is not evidence about "
              f"genotype-driven variation.")
        return 1
    print(f"  [PASS] all {drawn} villagers are wearing their own baked body.")
    return 0
