"""Measure an FBX inside Unity, in batch mode, without opening the editor.

Stage 6's acceptance criterion is "a 1.75 m character measures 1.75 m in
Unity". Session 21 measured the capsule villagers against `frames.csv` and
found them exact to the millimetre, which turned the capsules into a
calibrated ruler; this module lays an MPFB export against that ruler.

THE TRAP THIS MODULE EXISTS TO NOT FALL INTO. `Renderer.bounds` is a CACHED
volume, and on a SkinnedMeshRenderer, which is what an FBX with blendshapes
or bones becomes, it is not a measurement of the vertices. It read 2.662778
for a mesh whose vertices span 1.665890, and 1.948065 for one spanning
1.754592: plausible numbers, wrong by 60% and 11%. `Mesh.bounds` is no better,
because Unity leaves the mesh datablock in the FBX's own centimetre, Z-up
space and puts the correction on the transform. The only honest measurement is
the vertex positions pushed through `Transform.TransformPoint`, which is what
the C# below does. Both untrustworthy numbers are reported anyway, so a
regression can show they still disagree.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

MARKER = "[MEASURE]"

EDITOR_CS = r'''
using System.Text;
using UnityEditor;
using UnityEngine;

// Generated by mpfb/unity_measure.py. Not tracked, not part of the package.
public static class MeasureMpfbFbx
{
    private const string Marker = "[MEASURE]";

    public static void Run()
    {
        var sb = new StringBuilder();
        foreach (var guid in AssetDatabase.FindAssets("t:Model", new[] { "Assets/MpfbProbe" }))
        {
            var path = AssetDatabase.GUIDToAssetPath(guid);
            var importer = AssetImporter.GetAtPath(path) as ModelImporter;
            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);
            if (prefab == null) continue;

            var inst = Object.Instantiate(prefab);
            inst.transform.position = Vector3.zero;
            inst.transform.rotation = Quaternion.identity;
            inst.transform.localScale = Vector3.one;

            var renderers = inst.GetComponentsInChildren<Renderer>();
            sb.AppendLine($"{Marker} BEGIN {System.IO.Path.GetFileName(path)}");
            sb.AppendLine($"{Marker} useFileScale={importer?.useFileScale} " +
                          $"fileScale={(importer == null ? 0f : importer.fileScale).ToString("R", System.Globalization.CultureInfo.InvariantCulture)}");

            var hasV = false;
            Vector3 lo = Vector3.zero, hi = Vector3.zero;
            var blendShapes = 0;
            var bones = 0;
            foreach (var r in renderers)
            {
                Mesh mesh = r is SkinnedMeshRenderer smr
                    ? smr.sharedMesh
                    : r.GetComponent<MeshFilter>()?.sharedMesh;
                if (mesh == null) continue;
                blendShapes += mesh.blendShapeCount;
                bones += (r as SkinnedMeshRenderer)?.bones.Length ?? 0;
                foreach (var v in mesh.vertices)
                {
                    var w = r.transform.TransformPoint(v);
                    if (!hasV) { lo = w; hi = w; hasV = true; continue; }
                    lo = Vector3.Min(lo, w);
                    hi = Vector3.Max(hi, w);
                }
                Emit(sb, "cached_renderer_bounds", r.bounds.size);
                Emit(sb, "local_mesh_bounds", mesh.bounds.size);
            }
            sb.AppendLine($"{Marker} blendShapes={blendShapes} bones={bones}");
            if (hasV)
            {
                Emit(sb, "vertex_span", hi - lo);
                Emit(sb, "vertex_min", lo);
            }
            sb.AppendLine($"{Marker} END");
            Object.DestroyImmediate(inst);
        }
        Debug.Log(sb.ToString());
        EditorApplication.Exit(0);
    }

    // Invariant culture on purpose: this machine's locale is tr-TR, where the
    // decimal separator is a comma and a Python float() on the other side of
    // the log would either throw or silently read a thousands separator.
    private static void Emit(StringBuilder sb, string key, Vector3 v)
    {
        var c = System.Globalization.CultureInfo.InvariantCulture;
        sb.AppendLine($"{Marker} {key}=" +
                      $"{v.x.ToString("F6", c)},{v.y.ToString("F6", c)},{v.z.ToString("F6", c)}");
    }
}
'''


BODYCHECK_CS = r'''
using System.Text;
using ExtNPC.View;
using UnityEditor;
using UnityEngine;

// Generated by mpfb/unity_measure.py. Not tracked, not part of the package.
//
// The one path the EditMode suite cannot reach: HumanMesh.Bake against a REAL
// MPFB FBX. HumanMeshTests pins the normalisation arithmetic on synthetic
// boxes, which is worth having, but a synthetic box does not arrive in
// centimetres with Blender's Z as the up axis. This does.
public static class CheckMpfbBodies
{
    private const string Marker = "[BODYCHECK]";

    public static void Run()
    {
        var c = System.Globalization.CultureInfo.InvariantCulture;
        var sb = new StringBuilder();
        HumanMesh.Forget();

        foreach (var female in new[] { true, false })
        {
            string label = female ? "female" : "male";
            Mesh unit = HumanMesh.UnitBody(female);
            sb.AppendLine($"{Marker} BEGIN {label}");
            if (unit == null)
            {
                sb.AppendLine($"{Marker} installed=false");
                sb.AppendLine($"{Marker} END");
                continue;
            }

            Bounds b = unit.bounds;
            sb.AppendLine($"{Marker} installed=true");
            sb.AppendLine($"{Marker} verts={unit.vertexCount}");
            sb.AppendLine($"{Marker} authored_stature_m=" +
                          HumanMesh.AuthoredStature(female).ToString("F6", c));
            sb.AppendLine($"{Marker} unit_height=" + b.size.y.ToString("F6", c));
            sb.AppendLine($"{Marker} unit_min_y=" + b.min.y.ToString("F6", c));
            sb.AppendLine($"{Marker} unit_centre_x=" + b.center.x.ToString("F6", c));
            sb.AppendLine($"{Marker} unit_centre_z=" + b.center.z.ToString("F6", c));
            sb.AppendLine($"{Marker} unit_width_x=" + b.size.x.ToString("F6", c));
            sb.AppendLine($"{Marker} unit_depth_z=" + b.size.z.ToString("F6", c));

            // What VillagerView actually does, measured through a real
            // transform rather than by multiplying the numbers above: create
            // the object, scale it by a stature, read the renderer's vertices
            // back in world space.
            var go = new GameObject("probe");
            go.AddComponent<MeshFilter>().sharedMesh = unit;
            go.transform.position = Vector3.zero;
            go.transform.localScale = Vector3.one * 1.754592f;
            Vector3[] verts = unit.vertices;
            float lo = float.MaxValue, hi = float.MinValue;
            foreach (var v in verts)
            {
                float y = go.transform.TransformPoint(v).y;
                if (y < lo) lo = y;
                if (y > hi) hi = y;
            }
            sb.AppendLine($"{Marker} rendered_at_1p754592=" + (hi - lo).ToString("F6", c));
            sb.AppendLine($"{Marker} rendered_min_y=" + lo.ToString("F6", c));
            Object.DestroyImmediate(go);
            sb.AppendLine($"{Marker} END");
        }

        Debug.Log(sb.ToString());
        EditorApplication.Exit(0);
    }
}
'''


PORTRAIT_CS = r'''
using System.Text;
using ExtNPC.View;
using UnityEditor;
using UnityEngine;

// Generated by mpfb/unity_measure.py. Not tracked, not part of the package.
//
// Renders the inspector's portrait head to PNG files and reports statistics
// about them. The pictures are for a human; the statistics are so that a
// regression can fail without one. Needs a graphics device, so it is run
// WITHOUT -nographics, unlike everything else in this repository.
public static class CheckMpfbPortrait
{
    private const string Marker = "[PORTRAIT]";

    public static void Run()
    {
        var c = System.Globalization.CultureInfo.InvariantCulture;
        var sb = new StringBuilder();
        string outDir = System.Environment.GetEnvironmentVariable("EXTNPC_PORTRAIT_OUT");
        HumanMesh.Forget();

        sb.AppendLine($"{Marker} BEGIN device");
        sb.AppendLine($"{Marker} graphicsDeviceType=" + SystemInfo.graphicsDeviceType);
        sb.AppendLine($"{Marker} bodyInstalled=" + CharacterPortrait.BodyInstalled);
        sb.AppendLine($"{Marker} END");

        var host = new GameObject("PortraitHost");
        var portrait = CharacterPortrait.Create(host.transform);

        // Two villagers, two times each. The four pictures answer four
        // separate questions: is there a face, does it move, do two people
        // move differently, and is the backdrop the lineage colour.
        var subjects = new[]
        {
            ("Selin-24", true, 170.5, new Color(0.85f, 0.45f, 0.30f)),
            ("Tomas-28", false, 178.0, new Color(0.30f, 0.55f, 0.85f)),
        };
        double[] times = { 0.0, 3.7 };

        foreach (var (name, female, height, lineage) in subjects)
        {
            foreach (double t in times)
            {
                portrait.SetSubject(name, female, height, lineage);
                portrait.RenderFrame(t);
                RenderTexture rt = portrait.Texture;

                string tag = $"{name}_t{t.ToString("0.0", c)}";
                sb.AppendLine($"{Marker} BEGIN {tag}");
                if (rt == null)
                {
                    sb.AppendLine($"{Marker} rendered=false");
                    sb.AppendLine($"{Marker} END");
                    continue;
                }

                var shot = new Texture2D(rt.width, rt.height, TextureFormat.RGBA32, false);
                RenderTexture prev = RenderTexture.active;
                RenderTexture.active = rt;
                shot.ReadPixels(new Rect(0, 0, rt.width, rt.height), 0, 0);
                shot.Apply();
                RenderTexture.active = prev;

                Color32[] pixels = shot.GetPixels32();
                // GetPixels32 starts at the BOTTOM-left, and the bottom of a
                // portrait is shoulder, not backdrop. Reading pixels[0] as the
                // backdrop reported a white "sky" and a meaningless subject
                // fraction of 0.98. The top-left corner is the one that is
                // always empty.
                Color32 backdrop = pixels[(rt.height - 1) * rt.width];
                int subject = 0;
                int minX = rt.width, maxX = -1, minY = rt.height, maxY = -1;
                double sum = 0.0;
                for (int i = 0; i < pixels.Length; i++)
                {
                    Color32 p = pixels[i];
                    sum += (p.r + p.g + p.b) / 3.0;
                    int d = Mathf.Abs(p.r - backdrop.r) + Mathf.Abs(p.g - backdrop.g)
                            + Mathf.Abs(p.b - backdrop.b);
                    if (d <= 24) continue;
                    subject++;
                    int x = i % rt.width, y = i / rt.width;
                    if (x < minX) minX = x;
                    if (x > maxX) maxX = x;
                    if (y < minY) minY = y;
                    if (y > maxY) maxY = y;
                }

                sb.AppendLine($"{Marker} rendered=true");
                sb.AppendLine($"{Marker} subject_fraction=" +
                              (subject / (double)pixels.Length).ToString("F4", c));
                sb.AppendLine($"{Marker} mean_luma=" + (sum / pixels.Length).ToString("F2", c));
                sb.AppendLine($"{Marker} backdrop_rgb=" +
                              $"{backdrop.r},{backdrop.g},{backdrop.b}");
                sb.AppendLine($"{Marker} subject_box=" +
                              $"{minX},{minY},{maxX},{maxY}");

                if (!string.IsNullOrEmpty(outDir))
                {
                    System.IO.Directory.CreateDirectory(outDir);
                    string file = System.IO.Path.Combine(outDir, "portrait_" + tag + ".png");
                    System.IO.File.WriteAllBytes(file, shot.EncodeToPNG());
                    sb.AppendLine($"{Marker} png=" + file);
                }
                Object.DestroyImmediate(shot);
                sb.AppendLine($"{Marker} END");
            }
        }

        Object.DestroyImmediate(host);
        Debug.Log(sb.ToString());
        EditorApplication.Exit(0);
    }
}
'''


def check_portrait(project: Path, log_dir: Path, editor: Path,
                   png_dir: Path) -> dict:
    """Render the inspector portrait to PNG and report what came out.

    THE ONE THING IN THIS REPOSITORY THAT NEEDS A GRAPHICS DEVICE. Everything
    else runs under `-nographics`, which cannot render to a texture. So this
    launches the editor without that flag; on a machine with no device at all
    it will report the fact rather than pretend.
    """
    import os
    import run_unity_tests as rut

    rut.ensure_project(editor, project, log_dir)
    editor_dir = project / "Assets" / "Editor"
    editor_dir.mkdir(parents=True, exist_ok=True)
    (editor_dir / "CheckMpfbPortrait.cs").write_text(PORTRAIT_CS, encoding="utf-8")
    png_dir.mkdir(parents=True, exist_ok=True)

    log = log_dir / "mpfb-portrait.log"
    if log.exists():
        log.unlink()
    env = dict(os.environ, EXTNPC_PORTRAIT_OUT=str(png_dir))
    cmd = [str(editor), "-batchmode", "-accept-apiupdate",
           "-logFile", str(log), "-projectPath", str(project),
           "-executeMethod", "CheckMpfbPortrait.Run"]
    print("  $ " + " ".join(cmd))
    proc = subprocess.run(cmd, timeout=1800, env=env)
    print(f"  editor exited {proc.returncode}")
    if not log.exists():
        raise SystemExit("no editor log")
    return _parse(log.read_text(encoding="utf-8", errors="replace"),
                  marker="[PORTRAIT]")


def check_bodies(bodies_dir: Path, project: Path, log_dir: Path,
                 editor: Path) -> dict:
    """Install the two bodies into `project` and measure what HumanMesh made.

    Falsifiable by construction: if Bake ever stops folding the FBX's
    centimetre Z-up transform into the vertices, the unit height comes back as
    0.0175 instead of 1.0 and the rendered stature as 0.03 m instead of 1.75.
    """
    import run_unity_tests as rut

    rut.ensure_project(editor, project, log_dir)

    resources = project / "Assets" / "Resources" / "extnpc"
    resources.mkdir(parents=True, exist_ok=True)
    staged = 0
    for name in ("human_female.fbx", "human_male.fbx"):
        source = bodies_dir / name
        if source.exists():
            shutil.copy2(source, resources / name)
            staged += 1
    if staged == 0:
        raise SystemExit(f"no bodies to install from {bodies_dir}")

    editor_dir = project / "Assets" / "Editor"
    editor_dir.mkdir(parents=True, exist_ok=True)
    (editor_dir / "CheckMpfbBodies.cs").write_text(BODYCHECK_CS, encoding="utf-8")

    log = log_dir / "mpfb-bodycheck.log"
    code = rut._run_editor(editor, ["-projectPath", str(project),
                                    "-executeMethod", "CheckMpfbBodies.Run"],
                           log, timeout=1800)
    if code != 0:
        rut._print_log_errors(log)
        raise SystemExit(f"the editor exited {code}; see {log}")
    return _parse(log.read_text(encoding="utf-8", errors="replace"),
                  marker="[BODYCHECK]")


def measure(fbx_dir: Path, project: Path, log_dir: Path, editor: Path) -> dict:
    """Import every FBX in `fbx_dir` and report its true vertex extents."""
    import run_unity_tests as rut

    rut.ensure_project(editor, project, log_dir)

    probe = project / "Assets" / "MpfbProbe"
    if probe.exists():
        shutil.rmtree(probe)
    probe.mkdir(parents=True)
    editor_dir = project / "Assets" / "Editor"
    editor_dir.mkdir(parents=True, exist_ok=True)
    (editor_dir / "MeasureMpfbFbx.cs").write_text(EDITOR_CS, encoding="utf-8")

    staged = sorted(fbx_dir.glob("*.fbx"))
    if not staged:
        raise SystemExit(f"no FBX to measure in {fbx_dir}")
    for path in staged:
        shutil.copy2(path, probe / path.name)

    log = log_dir / "mpfb-measure.log"
    code = rut._run_editor(editor, ["-projectPath", str(project),
                                    "-executeMethod", "MeasureMpfbFbx.Run"],
                           log, timeout=1800)
    if code != 0:
        rut._print_log_errors(log)
        raise SystemExit(f"the editor exited {code}; see {log}")

    return _parse(log.read_text(encoding="utf-8", errors="replace"))


def _parse(text: str, marker: str = MARKER) -> dict:
    """Marker lines out of the editor log, into a dict per subject."""
    results: dict[str, dict] = {}
    current: str | None = None
    for raw in text.splitlines():
        if marker not in raw:
            continue
        body = raw.split(marker, 1)[1].strip()
        if body.startswith("BEGIN "):
            current = body[6:].strip()
            results[current] = {}
            continue
        if body == "END":
            current = None
            continue
        if current is None or "=" not in body:
            continue
        key, _, value = body.partition("=")
        key = key.strip()
        value = value.strip()
        if re.fullmatch(r"-?[\d.]+,-?[\d.]+,-?[\d.]+", value):
            results[current][key] = [float(part) for part in value.split(",")]
        elif re.fullmatch(r"-?[\d.]+([eE][-+]?\d+)?", value):
            results[current][key] = float(value)
        else:
            results[current][key] = value
    return results


def write_json(results: dict, path: Path) -> None:
    path.write_text(json.dumps(results, indent=2) + "\n", encoding="utf-8")
