"""What 600 real bodies cost, measured rather than assumed.

WHY NOW. UNITY_PLAN.md §4.3 sets the budget at 600 villagers at 60 fps, and
Stage 6 has just swapped a 500-vertex capsule for a 14.5k-vertex human. That is
a 29x change in geometry made in a commit whose tests are all about
millimetres, so the budget has to be re-measured before anyone relies on it.
Session 21 measured 67 to 143 fps at 69 CAPSULES and was explicit that nothing
there spoke to 600.

WHAT THIS MEASURES, AND WHAT IT DOES NOT. It times `Camera.Render()` on a
scene of N villager views, in the editor, offscreen, with no HUD and no
gameplay. That is the geometry and draw-call cost and nothing else. It is NOT
a frame rate: no player loop, no IMGUI, no input, and the editor is not a
build. Treat it as a floor on the cost, not as a prediction of the frame.

The capsule arm is run for the same N so the comparison is against this
project's own previous state rather than against a guess about what is fast.
"""

from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

MARKER = "[PERF]"

PERF_CS = r'''
using System.Diagnostics;
using System.Text;
using ExtNPC.Data;
using ExtNPC;
using ExtNPC.View;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using Debug = UnityEngine.Debug;

// Generated by mpfb/unity_perf.py. Not tracked, not part of the package.
public static class MeasureMpfbPerf
{
    private const string Marker = "[PERF]";
    private static readonly int[] Counts = { 28, 100, 300, 600, 1000 };

    public static void Run()
    {
        var c = System.Globalization.CultureInfo.InvariantCulture;
        var sb = new StringBuilder();
        HumanMesh.Forget();

        EditorSceneManager.NewScene(NewSceneSetup.DefaultGameObjects, NewSceneMode.Single);

        sb.AppendLine($"{Marker} BEGIN setup");
        sb.AppendLine($"{Marker} body_installed=" + HumanMesh.Available);
        sb.AppendLine($"{Marker} device=" + SystemInfo.graphicsDeviceType);
        Mesh unit = HumanMesh.UnitBody(true);
        sb.AppendLine($"{Marker} mesh_verts=" +
            (unit != null ? unit.vertexCount : PrimitiveMeshes.Capsule.vertexCount).ToString(c));
        sb.AppendLine($"{Marker} END");

        var camGo = new GameObject("PerfCam");
        var cam = camGo.AddComponent<Camera>();
        cam.fieldOfView = 42f;
        cam.clearFlags = CameraClearFlags.SolidColor;
        cam.backgroundColor = new Color(0.07f, 0.08f, 0.10f);
        cam.farClipPlane = 500f;
        camGo.transform.position = new Vector3(0f, 34f, -52f);
        camGo.transform.LookAt(Vector3.zero);
        var rt = new RenderTexture(1280, 720, 24);
        rt.Create();
        cam.targetTexture = rt;

        var lightGo = new GameObject("Sun");
        var sun = lightGo.AddComponent<Light>();
        sun.type = LightType.Directional;
        lightGo.transform.rotation = Quaternion.Euler(50f, -30f, 0f);

        var probe = new Texture2D(1, 1, TextureFormat.RGBA32, false);
        var root = new GameObject("Crowd").transform;
        var projection = MapProjection.Default;

        foreach (int n in Counts)
        {
            Populate(root, n, projection);

            // Warm up: the first render after a scene change pays for shader
            // variants and buffer allocation, and quoting that as the cost of
            // drawing bodies would be measuring the editor rather than them.
            for (int i = 0; i < 5; i++) RenderAndSync(cam, probe, rt);

            const int reps = 40;
            double best = double.MaxValue, total = 0.0;
            for (int i = 0; i < reps; i++)
            {
                var sw = Stopwatch.StartNew();
                RenderAndSync(cam, probe, rt);
                sw.Stop();
                double one = sw.Elapsed.TotalMilliseconds;
                total += one;
                if (one < best) best = one;
            }

            sb.AppendLine($"{Marker} BEGIN n{n}");
            sb.AppendLine($"{Marker} count=" + n.ToString(c));
            sb.AppendLine($"{Marker} ms_mean=" + (total / reps).ToString("F3", c));
            // The MINIMUM is the honest one on a machine that is also running
            // an editor, a browser and whatever else: noise can only add time,
            // so the fastest observed pass is the closest to the real cost.
            sb.AppendLine($"{Marker} ms_min=" + best.ToString("F3", c));
            sb.AppendLine($"{Marker} implied_fps_min=" + (1000.0 / best).ToString("F1", c));
            sb.AppendLine($"{Marker} END");
        }

        cam.targetTexture = null;
        rt.Release();
        Debug.Log(sb.ToString());
        EditorApplication.Exit(0);
    }

    /// <summary>
    /// Render, and WAIT for the GPU to have actually done it.
    ///
    /// Camera.Render() only submits. The first version of this benchmark timed
    /// submission alone and reported 1000 bodies at 7.7 ms against 1000
    /// capsules at 11.1 ms: real bodies apparently FASTER than primitives, and
    /// the ratio not even monotone in N, which is what a measurement of
    /// something other than the intended thing looks like. Reading a single
    /// pixel back stalls the CPU until the frame is complete, so the number
    /// includes the geometry the GPU was asked to chew.
    /// </summary>
    private static void RenderAndSync(Camera cam, Texture2D probe, RenderTexture rt)
    {
        cam.Render();
        RenderTexture prev = RenderTexture.active;
        RenderTexture.active = rt;
        probe.ReadPixels(new Rect(0, 0, 1, 1), 0, 0);
        probe.Apply();
        RenderTexture.active = prev;
    }

    /// <summary>
    /// N villagers on the map, from a synthetic frame.
    ///
    /// Synthetic on purpose: the demo bundle has 28 people and the budget is
    /// about 600, so the rows are generated rather than read. Nothing about
    /// the numbers is a simulation result and none of it is shown to anyone;
    /// this is a geometry benchmark, and the only fields that matter to it are
    /// position, stature and sex.
    /// </summary>
    private static void Populate(Transform root, int n, in MapProjection projection)
    {
        foreach (Transform t in root) Object.DestroyImmediate(t.gameObject);

        Material shared = new Material(Shader.Find("Universal Render Pipeline/Lit")
                                       ?? Shader.Find("Standard"));
        int side = Mathf.CeilToInt(Mathf.Sqrt(n));
        for (int i = 0; i < n; i++)
        {
            var view = VillagerView.Create(root, shared);
            float gx = (i % side) / (float)side * 90f + 5f;
            float gy = (i / side) / (float)side * 90f + 5f;
            var row = new FrameRow
            {
                Name = "perf" + i,
                X = gx,
                Y = gy,
                HeightCm = 150.0 + (i % 45),
                IsFemale = (i % 2) == 0,
                Color = (Color32)Color.HSVToRGB((i % 12) / 12f, 0.6f, 0.9f),
            };
            view.Apply(row, projection);
        }
    }
}
'''


def measure(project: Path, log_dir: Path, editor: Path, with_bodies: bool) -> dict:
    import shutil
    import run_unity_tests as rut
    from mpfb import unity_measure

    rut.ensure_project(editor, project, log_dir)
    editor_dir = project / "Assets" / "Editor"
    editor_dir.mkdir(parents=True, exist_ok=True)
    (editor_dir / "MeasureMpfbPerf.cs").write_text(PERF_CS, encoding="utf-8")

    resources = project / "Assets" / "Resources" / "extnpc"
    parked = project / "Assets" / "_parked_perf"
    tag = "bodies" if with_bodies else "capsules"
    moved = False
    if not with_bodies and resources.is_dir():
        if parked.exists():
            shutil.rmtree(parked)
        shutil.move(str(resources), str(parked))
        meta = resources.with_suffix(resources.suffix + ".meta")
        if meta.exists():
            meta.unlink()
        moved = True

    try:
        log = log_dir / f"mpfb-perf-{tag}.log"
        if log.exists():
            log.unlink()
        cmd = [str(editor), "-batchmode", "-accept-apiupdate",
               "-logFile", str(log), "-projectPath", str(project),
               "-executeMethod", "MeasureMpfbPerf.Run"]
        print(f"  timing {tag}")
        subprocess.run(cmd, timeout=3600, env=dict(os.environ))
        if not log.exists():
            raise SystemExit("no editor log")
        return unity_measure._parse(
            log.read_text(encoding="utf-8", errors="replace"), marker=MARKER)
    finally:
        if moved:
            if resources.exists():
                shutil.rmtree(resources)
            shutil.move(str(parked), str(resources))


def both(project: Path, log_dir: Path, editor: Path) -> dict:
    return {
        "capsules": measure(project, log_dir, editor, False),
        "bodies": measure(project, log_dir, editor, True),
    }


def write_json(results: dict, path: Path) -> None:
    path.write_text(json.dumps(results, indent=2) + "\n", encoding="utf-8")
