"""Measure an FBX inside Unity, in batch mode, without opening the editor.

Stage 6's acceptance criterion is "a 1.75 m character measures 1.75 m in
Unity". Session 21 measured the capsule villagers against `frames.csv` and
found them exact to the millimetre, which turned the capsules into a
calibrated ruler; this module lays an MPFB export against that ruler.

THE TRAP THIS MODULE EXISTS TO NOT FALL INTO. `Renderer.bounds` is a CACHED
volume, and on a SkinnedMeshRenderer, which is what an FBX with blendshapes
or bones becomes, it is not a measurement of the vertices. It read 2.662778
for a mesh whose vertices span 1.665890, and 1.948065 for one spanning
1.754592: plausible numbers, wrong by 60% and 11%. `Mesh.bounds` is no better,
because Unity leaves the mesh datablock in the FBX's own centimetre, Z-up
space and puts the correction on the transform. The only honest measurement is
the vertex positions pushed through `Transform.TransformPoint`, which is what
the C# below does. Both untrustworthy numbers are reported anyway, so a
regression can show they still disagree.
"""

from __future__ import annotations

import json
import re
import shutil
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

MARKER = "[MEASURE]"

EDITOR_CS = r'''
using System.Text;
using UnityEditor;
using UnityEngine;

// Generated by mpfb/unity_measure.py. Not tracked, not part of the package.
public static class MeasureMpfbFbx
{
    private const string Marker = "[MEASURE]";

    public static void Run()
    {
        var sb = new StringBuilder();
        foreach (var guid in AssetDatabase.FindAssets("t:Model", new[] { "Assets/MpfbProbe" }))
        {
            var path = AssetDatabase.GUIDToAssetPath(guid);
            var importer = AssetImporter.GetAtPath(path) as ModelImporter;
            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);
            if (prefab == null) continue;

            var inst = Object.Instantiate(prefab);
            inst.transform.position = Vector3.zero;
            inst.transform.rotation = Quaternion.identity;
            inst.transform.localScale = Vector3.one;

            var renderers = inst.GetComponentsInChildren<Renderer>();
            sb.AppendLine($"{Marker} BEGIN {System.IO.Path.GetFileName(path)}");
            sb.AppendLine($"{Marker} useFileScale={importer?.useFileScale} " +
                          $"fileScale={(importer == null ? 0f : importer.fileScale).ToString("R", System.Globalization.CultureInfo.InvariantCulture)}");

            var hasV = false;
            Vector3 lo = Vector3.zero, hi = Vector3.zero;
            var blendShapes = 0;
            var bones = 0;
            foreach (var r in renderers)
            {
                Mesh mesh = r is SkinnedMeshRenderer smr
                    ? smr.sharedMesh
                    : r.GetComponent<MeshFilter>()?.sharedMesh;
                if (mesh == null) continue;
                blendShapes += mesh.blendShapeCount;
                bones += (r as SkinnedMeshRenderer)?.bones.Length ?? 0;
                foreach (var v in mesh.vertices)
                {
                    var w = r.transform.TransformPoint(v);
                    if (!hasV) { lo = w; hi = w; hasV = true; continue; }
                    lo = Vector3.Min(lo, w);
                    hi = Vector3.Max(hi, w);
                }
                Emit(sb, "cached_renderer_bounds", r.bounds.size);
                Emit(sb, "local_mesh_bounds", mesh.bounds.size);
            }
            sb.AppendLine($"{Marker} blendShapes={blendShapes} bones={bones}");
            if (hasV)
            {
                Emit(sb, "vertex_span", hi - lo);
                Emit(sb, "vertex_min", lo);
            }
            sb.AppendLine($"{Marker} END");
            Object.DestroyImmediate(inst);
        }
        Debug.Log(sb.ToString());
        EditorApplication.Exit(0);
    }

    // Invariant culture on purpose: this machine's locale is tr-TR, where the
    // decimal separator is a comma and a Python float() on the other side of
    // the log would either throw or silently read a thousands separator.
    private static void Emit(StringBuilder sb, string key, Vector3 v)
    {
        var c = System.Globalization.CultureInfo.InvariantCulture;
        sb.AppendLine($"{Marker} {key}=" +
                      $"{v.x.ToString("F6", c)},{v.y.ToString("F6", c)},{v.z.ToString("F6", c)}");
    }
}
'''


def measure(fbx_dir: Path, project: Path, log_dir: Path, editor: Path) -> dict:
    """Import every FBX in `fbx_dir` and report its true vertex extents."""
    import run_unity_tests as rut

    rut.ensure_project(editor, project, log_dir)

    probe = project / "Assets" / "MpfbProbe"
    if probe.exists():
        shutil.rmtree(probe)
    probe.mkdir(parents=True)
    editor_dir = project / "Assets" / "Editor"
    editor_dir.mkdir(parents=True, exist_ok=True)
    (editor_dir / "MeasureMpfbFbx.cs").write_text(EDITOR_CS, encoding="utf-8")

    staged = sorted(fbx_dir.glob("*.fbx"))
    if not staged:
        raise SystemExit(f"no FBX to measure in {fbx_dir}")
    for path in staged:
        shutil.copy2(path, probe / path.name)

    log = log_dir / "mpfb-measure.log"
    code = rut._run_editor(editor, ["-projectPath", str(project),
                                    "-executeMethod", "MeasureMpfbFbx.Run"],
                           log, timeout=1800)
    if code != 0:
        rut._print_log_errors(log)
        raise SystemExit(f"the editor exited {code}; see {log}")

    return _parse(log.read_text(encoding="utf-8", errors="replace"))


def _parse(text: str) -> dict:
    """Marker lines out of the editor log, into a dict per FBX."""
    results: dict[str, dict] = {}
    current: str | None = None
    for raw in text.splitlines():
        if MARKER not in raw:
            continue
        body = raw.split(MARKER, 1)[1].strip()
        if body.startswith("BEGIN "):
            current = body[6:].strip()
            results[current] = {}
            continue
        if body == "END":
            current = None
            continue
        if current is None or "=" not in body:
            continue
        key, _, value = body.partition("=")
        key = key.strip()
        value = value.strip()
        if re.fullmatch(r"-?[\d.]+,-?[\d.]+,-?[\d.]+", value):
            results[current][key] = [float(part) for part in value.split(",")]
        elif re.fullmatch(r"-?[\d.]+([eE][-+]?\d+)?", value):
            results[current][key] = float(value)
        else:
            results[current][key] = value
    return results


def write_json(results: dict, path: Path) -> None:
    path.write_text(json.dumps(results, indent=2) + "\n", encoding="utf-8")
