"""Enter Play mode, screenshot the running viewer, and report what was live.

WHY THIS EXISTS, and it is not belt and braces. Everything else in `mpfb/`
runs in EditMode, and EditMode is a different machine. The body pipeline was
verified there, passed, reported 14,517 vertices and an exact stature, and
then produced an invisible village the first time it ran in Play: Unity
imports models with `isReadable = false` and drops the CPU copy once the mesh
is uploaded, and `Mesh.CombineMeshes` then returns an EMPTY mesh rather than
failing. Before the first frame the CPU copy is still there and the same call
works.

So an EditMode check could not see the defect that mattered most, and the only
honest verification of "the viewer works" is to run the viewer.

WHAT IT DOES. Builds a scene, points it at a bundle, turns OFF the domain
reload that would otherwise wipe this harness's own statics on entering Play,
enters Play, waits for the loader, selects a villager, and captures both the
world camera and the portrait's own render target. NOT the Game view:
`ScreenCapture.CaptureScreenshot` needs one, and a batch editor has none.
"""

from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

MARKER = "[PLAY]"

PLAY_CS = r'''
using System.Text;
using ExtNPC;
using ExtNPC.View;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

// Generated by mpfb/unity_playmode.py. Not tracked, not part of the package.
public static class CaptureMpfbPlaymode
{
    private const string Marker = "[PLAY]";

    private static readonly StringBuilder Log = new StringBuilder();
    private static string _outDir;
    private static string _shot;
    private static int _frames;
    private static int _phase;

    public static void Run()
    {
        _outDir = System.Environment.GetEnvironmentVariable("EXTNPC_PLAY_OUT");
        string bundle = System.Environment.GetEnvironmentVariable("EXTNPC_BUNDLE");

        Line("BEGIN setup");
        Line("device=" + SystemInfo.graphicsDeviceType);
        Line("body_installed=" + HumanMesh.Available);
        Line("END");

        EditorSceneManager.NewScene(NewSceneSetup.DefaultGameObjects,
                                    NewSceneMode.Single);
        ExtNPC.Editor.SceneSetup.CreateViewer();
        var root = GameObject.Find("extNPC World");
        var loader = root.GetComponent<ExtNpcWorldLoader>();
        loader.absolutePathOverride = bundle;
        loader.loadOnStart = true;

        // Without this, entering Play reloads the domain, every static above is
        // reset and this class's update callback is gone: the editor sits in
        // Play forever and the run times out having produced nothing.
        EditorSettings.enterPlayModeOptionsEnabled = true;
        EditorSettings.enterPlayModeOptions = EnterPlayModeOptions.DisableDomainReload;

        EditorApplication.update += Tick;
        EditorApplication.EnterPlaymode();
    }

    private static void Tick()
    {
        if (!EditorApplication.isPlaying) return;
        _frames++;

        // Phase 0: let Start() run, the bundle load, and the first frames draw.
        if (_phase == 0)
        {
            if (_frames < 60) return;
            var root = GameObject.Find("extNPC World");
            var renderer = root != null ? root.GetComponent<WorldRenderer>() : null;
            var inspector = root != null ? root.GetComponent<VillagerInspector>() : null;
            var loader = root != null ? root.GetComponent<ExtNpcWorldLoader>() : null;

            Line("BEGIN play");
            Line("is_playing=" + EditorApplication.isPlaying);
            Line("bundle_loaded=" + (loader != null && loader.Bundle != null));
            Line("visible_count=" + (renderer != null ? renderer.VisibleCount : -1));
            Line("body_installed=" + HumanMesh.Available);

            string pick = null;
            float best = -1f;
            int withGeometry = 0;
            Transform villagers = null;
            foreach (Transform t in root.transform)
            {
                if (t.name == "Villagers") villagers = t;
            }
            if (villagers != null)
            {
                foreach (Transform t in villagers)
                {
                    if (!t.gameObject.activeSelf) continue;
                    var mf = t.GetComponent<MeshFilter>();
                    // THE CHECK THAT WOULD HAVE CAUGHT THE INVISIBLE VILLAGE.
                    // A body with an empty mesh is active, counted, selectable
                    // and not there; only a vertex count tells them apart.
                    if (mf != null && mf.sharedMesh != null &&
                        mf.sharedMesh.vertexCount > 0) withGeometry++;
                    if (t.localScale.y > best) { best = t.localScale.y; pick = t.name; }
                }
            }
            Line("bodies_with_geometry=" + withGeometry);
            Line("tallest=" + pick);
            Line("END");

            if (inspector != null && pick != null) inspector.Select(pick);
            _phase = 1;
            _frames = 0;
            return;
        }

        // Phase 1: let the inspector's Update build and render the portrait.
        if (_phase == 1)
        {
            if (_frames < 30) return;
            var root = GameObject.Find("extNPC World");
            var inspector = root.GetComponent<VillagerInspector>();
            Line("BEGIN portrait");
            Line("selected=" + inspector.SelectedName);
            Line("portrait_is_live=" + inspector.PortraitIsLive);
            Line("END");

            System.IO.Directory.CreateDirectory(_outDir);
            _shot = System.IO.Path.Combine(_outDir, "playmode_world.png");

            // NOT ScreenCapture.CaptureScreenshot. It captures the Game VIEW,
            // and a batch editor has no Game view: it returns without error and
            // never writes a file, which is what the first run of this harness
            // reported. Rendering the camera to a texture works headlessly. The
            // cost is that IMGUI is not in the picture, so the panel is
            // captured separately from its own render target below.
            var cam = Camera.main;
            bool ok = false;
            if (cam != null) ok = Grab(cam, _shot);
            Line("BEGIN capture");
            Line("world_png_written=" + ok);
            if (ok) Line("world_png=" + _shot);

            // And the view the "go to villager" button gives, which is the
            // difference between a grey plane with specks and a person.
            var closeup = System.IO.Path.Combine(_outDir, "playmode_closeup.png");
            bool closeOk = false;
            var orbit = cam != null ? cam.GetComponent<OrbitCamera>() : null;
            var rendererForFocus = root.GetComponent<WorldRenderer>();
            if (orbit != null && rendererForFocus != null)
            {
                Transform body = null;
                foreach (Transform t in root.transform)
                {
                    if (t.name != "Villagers") continue;
                    foreach (Transform v in t)
                    {
                        if (v.gameObject.activeSelf && v.name == inspector.SelectedName)
                            body = v;
                    }
                }
                if (body != null)
                {
                    orbit.Focus(new Vector3(body.position.x, 0f, body.position.z),
                                body.localScale.y);
                    closeOk = Grab(cam, closeup);
                }
            }
            Line("closeup_png_written=" + closeOk);
            if (closeOk) Line("closeup_png=" + closeup);

            var face = System.IO.Path.Combine(_outDir, "playmode_portrait.png");
            Texture portrait = inspector.PortraitTexture;
            bool faceOk = portrait is RenderTexture rt2 && Save(rt2, face);
            Line("portrait_png_written=" + faceOk);
            if (faceOk) Line("portrait_png=" + face);
            Line("END");

            EditorApplication.update -= Tick;
            Debug.Log(Log.ToString());
            EditorApplication.isPlaying = false;
            EditorApplication.Exit(ok && faceOk ? 0 : 1);
        }
    }

    private static bool Grab(Camera cam, string path)
    {
        var rt = new RenderTexture(1280, 720, 24) { antiAliasing = 2 };
        rt.Create();
        RenderTexture previousTarget = cam.targetTexture;
        cam.targetTexture = rt;
        cam.Render();
        cam.targetTexture = previousTarget;
        bool ok = Save(rt, path);
        rt.Release();
        Object.DestroyImmediate(rt);
        return ok;
    }

    private static bool Save(RenderTexture rt, string path)
    {
        var shot = new Texture2D(rt.width, rt.height, TextureFormat.RGBA32, false);
        RenderTexture prev = RenderTexture.active;
        RenderTexture.active = rt;
        shot.ReadPixels(new Rect(0, 0, rt.width, rt.height), 0, 0);
        shot.Apply();
        RenderTexture.active = prev;
        System.IO.File.WriteAllBytes(path, shot.EncodeToPNG());
        Object.DestroyImmediate(shot);
        return System.IO.File.Exists(path);
    }

    private static void Line(string s) => Log.AppendLine(Marker + " " + s);
}
'''


def capture(project: Path, log_dir: Path, editor: Path, bundle: Path,
            out_dir: Path) -> dict:
    """Run the viewer in Play mode and bring back a screenshot plus the facts."""
    import run_unity_tests as rut
    from mpfb import unity_measure

    rut.ensure_project(editor, project, log_dir)
    editor_dir = project / "Assets" / "Editor"
    editor_dir.mkdir(parents=True, exist_ok=True)
    (editor_dir / "CaptureMpfbPlaymode.cs").write_text(PLAY_CS, encoding="utf-8")
    out_dir.mkdir(parents=True, exist_ok=True)

    log = log_dir / "mpfb-playmode.log"
    if log.exists():
        log.unlink()
    env = dict(os.environ,
               EXTNPC_BUNDLE=str(bundle),
               EXTNPC_PLAY_OUT=str(out_dir))
    cmd = [str(editor), "-batchmode", "-accept-apiupdate",
           "-logFile", str(log), "-projectPath", str(project),
           "-executeMethod", "CaptureMpfbPlaymode.Run"]
    print("  entering play mode")
    proc = subprocess.run(cmd, timeout=1800, env=env)
    print(f"  editor exited {proc.returncode}")
    if not log.exists():
        raise SystemExit("no editor log")
    return unity_measure._parse(
        log.read_text(encoding="utf-8", errors="replace"), marker=MARKER)


def write_json(results: dict, path: Path) -> None:
    path.write_text(json.dumps(results, indent=2) + "\n", encoding="utf-8")
