"""Photograph the village, with bodies installed and without.

WHY. UNITY_PLAN.md Stage 6 ends "replace capsules with one shared human mesh.
Everyone identical, but they are people now." That is a claim about what the
screen looks like, and no test result can settle it. `HumanMeshTests` pins the
normalisation arithmetic and `check_bodies` pins the import, but neither has
ever seen a village.

THE A/B IS THE POINT. One run with `Assets/Resources/extnpc/` in place and one
with it moved aside gives two pictures of the same year, the same seed and the
same camera, differing only in whether a body asset existed. That makes
"villagers are people now" falsifiable instead of decorative: if the two
pictures came back identical, the mesh is not reaching `VillagerView` and the
whole of the previous commit is inert.

Moving the folder from PYTHON rather than adding a switch to `HumanMesh` is
deliberate. A production class should not grow a "pretend you found nothing"
flag so that a test can use it; the filesystem already has one.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from pathlib import Path

MARKER = "[VILLAGE]"

VILLAGE_CS = r'''
using System.Text;
using ExtNPC;
using ExtNPC.View;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

// Generated by mpfb/unity_village.py. Not tracked, not part of the package.
public static class ShootMpfbVillage
{
    private const string Marker = "[VILLAGE]";

    public static void Run()
    {
        var c = System.Globalization.CultureInfo.InvariantCulture;
        var sb = new StringBuilder();
        string bundle = System.Environment.GetEnvironmentVariable("EXTNPC_BUNDLE");
        string outDir = System.Environment.GetEnvironmentVariable("EXTNPC_VILLAGE_OUT");
        string tag = System.Environment.GetEnvironmentVariable("EXTNPC_VILLAGE_TAG");

        HumanMesh.Forget();
        EditorSceneManager.NewScene(NewSceneSetup.DefaultGameObjects,
                                    NewSceneMode.Single);
        // Fully qualified: UnityEditor.SceneManagement also has a SceneSetup.
        ExtNPC.Editor.SceneSetup.CreateViewer();

        var root = GameObject.Find("extNPC World");
        var loader = root.GetComponent<ExtNpcWorldLoader>();
        var renderer = root.GetComponent<WorldRenderer>();
        loader.absolutePathOverride = bundle;
        loader.loadOnStart = false;

        // Awake does not run in EditMode: Unity only calls it on components
        // whose class is marked ExecuteAlways, and WorldRenderer is not, quite
        // rightly, since it is a play-time viewer. It is what creates the
        // Villagers root and subscribes to the loader, and without it Render
        // returns immediately on a null bundle and the shot comes back as an
        // empty field. Reflection here rather than ExecuteAlways on the class,
        // because a screenshot harness must not change what it photographs.
        Invoke(renderer, "Awake");

        sb.AppendLine($"{Marker} BEGIN load");
        bool loaded = loader.Load();
        sb.AppendLine($"{Marker} loaded=" + loaded);
        if (!loaded)
        {
            sb.AppendLine($"{Marker} END");
            Debug.Log(sb.ToString());
            EditorApplication.Exit(1);
            return;
        }
        int lastTick = loader.Bundle.LastTick;
        sb.AppendLine($"{Marker} last_tick=" + lastTick.ToString(c));
        sb.AppendLine($"{Marker} body_installed=" + HumanMesh.Available);
        sb.AppendLine($"{Marker} END");

        // Update() does not run in EditMode, so the frame is drawn explicitly.
        renderer.Render(lastTick);

        sb.AppendLine($"{Marker} BEGIN scene");
        sb.AppendLine($"{Marker} visible_count=" + renderer.VisibleCount.ToString(c));
        sb.AppendLine($"{Marker} headcount_ok=" + renderer.CheckHeadcount(lastTick, false));

        // A villager to stand next to, and the tallest one so the close shot
        // is of an adult rather than of a toddler's forehead.
        Transform villagers = FindVillagerRoot(root.transform);
        Transform subject = null;
        float best = -1f;
        int drawn = 0;
        foreach (Transform t in villagers)
        {
            if (!t.gameObject.activeSelf) continue;
            drawn++;
            float h = t.localScale.y;
            if (h > best) { best = h; subject = t; }
        }
        sb.AppendLine($"{Marker} bodies_in_scene=" + drawn.ToString(c));
        sb.AppendLine($"{Marker} tallest_local_scale_y=" + best.ToString("F4", c));
        sb.AppendLine($"{Marker} END");

        Shoot(sb, outDir, $"village_wide_{tag}",
              new Vector3(0f, 34f, -52f), new Vector3(0f, 0f, 0f), 42f);

        if (subject != null)
        {
            // Eye level with the villager, four metres out. This is the shot
            // that answers the question; the wide one only shows dots.
            Vector3 p = subject.position;
            float eye = p.y + best * 0.9f;
            Shoot(sb, outDir, $"village_close_{tag}",
                  new Vector3(p.x + 2.6f, eye, p.z - 3.1f),
                  new Vector3(p.x, eye - 0.15f, p.z), 40f);
        }

        Debug.Log(sb.ToString());
        EditorApplication.Exit(0);
    }

    private static void Invoke(object target, string method)
    {
        var m = target.GetType().GetMethod(method,
            System.Reflection.BindingFlags.Instance |
            System.Reflection.BindingFlags.NonPublic |
            System.Reflection.BindingFlags.Public);
        if (m == null) throw new System.Exception($"no method {method}");
        m.Invoke(target, null);
    }

    private static Transform FindVillagerRoot(Transform root)
    {
        foreach (Transform t in root)
        {
            if (t.name == "Villagers") return t;
        }
        return root;
    }

    private static void Shoot(StringBuilder sb, string outDir, string name,
                              Vector3 from, Vector3 lookAt, float fov)
    {
        var c = System.Globalization.CultureInfo.InvariantCulture;
        var camGo = new GameObject("ShotCam");
        var cam = camGo.AddComponent<Camera>();
        cam.fieldOfView = fov;
        cam.clearFlags = CameraClearFlags.SolidColor;
        cam.backgroundColor = new Color(0.07f, 0.08f, 0.10f);
        cam.nearClipPlane = 0.05f;
        cam.farClipPlane = 500f;
        camGo.transform.position = from;
        camGo.transform.LookAt(lookAt);

        var rt = new RenderTexture(880, 520, 24) { antiAliasing = 2 };
        rt.Create();
        cam.targetTexture = rt;
        cam.Render();

        var shot = new Texture2D(rt.width, rt.height, TextureFormat.RGBA32, false);
        RenderTexture prev = RenderTexture.active;
        RenderTexture.active = rt;
        shot.ReadPixels(new Rect(0, 0, rt.width, rt.height), 0, 0);
        shot.Apply();
        RenderTexture.active = prev;

        sb.AppendLine($"{Marker} BEGIN {name}");
        if (!string.IsNullOrEmpty(outDir))
        {
            System.IO.Directory.CreateDirectory(outDir);
            string file = System.IO.Path.Combine(outDir, name + ".png");
            System.IO.File.WriteAllBytes(file, shot.EncodeToPNG());
            sb.AppendLine($"{Marker} png=" + file);
        }
        double sum = 0.0;
        Color32[] px = shot.GetPixels32();
        foreach (var p in px) sum += (p.r + p.g + p.b) / 3.0;
        sb.AppendLine($"{Marker} mean_luma=" + (sum / px.Length).ToString("F2", c));
        sb.AppendLine($"{Marker} END");

        cam.targetTexture = null;
        RenderTexture.active = null;
        rt.Release();
        Object.DestroyImmediate(shot);
        Object.DestroyImmediate(rt);
        Object.DestroyImmediate(camGo);
    }
}
'''


def shoot(project: Path, log_dir: Path, editor: Path, bundle: Path,
          png_dir: Path, with_bodies: bool) -> dict:
    """One pass. `with_bodies=False` moves the Resources folder aside first."""
    import run_unity_tests as rut
    from mpfb import unity_measure

    rut.ensure_project(editor, project, log_dir)
    editor_dir = project / "Assets" / "Editor"
    editor_dir.mkdir(parents=True, exist_ok=True)
    (editor_dir / "ShootMpfbVillage.cs").write_text(VILLAGE_CS, encoding="utf-8")
    png_dir.mkdir(parents=True, exist_ok=True)

    resources = project / "Assets" / "Resources" / "extnpc"
    parked = project / "Assets" / "_parked_extnpc"
    tag = "bodies" if with_bodies else "capsules"

    moved = False
    if not with_bodies and resources.is_dir():
        if parked.exists():
            shutil.rmtree(parked)
        shutil.move(str(resources), str(parked))
        # The .meta beside the folder has to go too, or Unity restores it as an
        # empty directory and logs a warning about a stray meta file.
        meta = resources.with_suffix(resources.suffix + ".meta")
        if meta.exists():
            meta.unlink()
        moved = True

    try:
        log = log_dir / f"mpfb-village-{tag}.log"
        if log.exists():
            log.unlink()
        env = dict(os.environ,
                   EXTNPC_BUNDLE=str(bundle),
                   EXTNPC_VILLAGE_OUT=str(png_dir),
                   EXTNPC_VILLAGE_TAG=tag)
        cmd = [str(editor), "-batchmode", "-accept-apiupdate",
               "-logFile", str(log), "-projectPath", str(project),
               "-executeMethod", "ShootMpfbVillage.Run"]
        print(f"  shooting {tag}")
        proc = subprocess.run(cmd, timeout=1800, env=env)
        if not log.exists():
            raise SystemExit("no editor log")
        result = unity_measure._parse(
            log.read_text(encoding="utf-8", errors="replace"), marker=MARKER)
        result["_exit"] = {"code": proc.returncode}
        return result
    finally:
        if moved:
            if resources.exists():
                shutil.rmtree(resources)
            shutil.move(str(parked), str(resources))


def both(project: Path, log_dir: Path, editor: Path, bundle: Path,
         png_dir: Path) -> dict:
    return {
        "capsules": shoot(project, log_dir, editor, bundle, png_dir, False),
        "bodies": shoot(project, log_dir, editor, bundle, png_dir, True),
    }


def write_json(results: dict, path: Path) -> None:
    path.write_text(json.dumps(results, indent=2) + "\n", encoding="utf-8")
